# Generated by Django 4.1.7 on 2023-03-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeStampedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="techusers.timestampedmodel",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="max 255 chars", max_length=255),
                ),
                ("from_email", models.EmailField(max_length=254, verbose_name="email")),
                ("recipients", models.TextField(verbose_name="recivers email")),
                ("reply_to", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("template", models.IntegerField()),
                ("sent_timestamp", models.DateTimeField(null=True)),
                ("attachment1", models.TextField(blank=True)),
            ],
            bases=("techusers.timestampedmodel",),
        ),
    ]
