# Generated by Django 3.2.16 on 2022-12-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_projectsupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsupload',
            old_name='title',
            new_name='file_name',
        ),
    ]
