# Generated by Django 4.0 on 2023-02-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='date sent')),
                ('recipient', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254, verbose_name='sender')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'email queue',
                'verbose_name_plural': 'email queues',
                'ordering': ['date'],
            },
        ),
    ]
