# Generated by Django 4.1.7 on 2023-03-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "techblog",
            "0002_postfield_author_postfield_tags_alter_postfield_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="postfield",
            name="tags",
            field=models.ManyToManyField(to="techblog.tag"),
        ),
    ]
