# Generated by Django 3.2.16 on 2022-12-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('order_reference', models.CharField(max_length=50)),
                ('order_title', models.CharField(choices=[('website design', 'website design'), ('database administrator', 'database administrator'), ('web researcher', 'web researcher'), ('website maintenance', 'website maintenance'), ('social media graphics', 'social media graphics'), ('logos and branding', 'logos and branding'), ('content expert', 'content expert')], max_length=30)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('S', 'successful'), ('A', 'awaiting'), ('P', 'progress'), ('F', 'failed')], default='A', max_length=1)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_description', models.TextField()),
            ],
            options={
                'ordering': ['firstname'],
            },
        ),
    ]
