# Generated by Django 3.2.16 on 2022-12-09 23:50

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_date_order_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.CharField(default=orders.models.generate_id, max_length=50),
        ),
    ]
