# Generated by Django 3.2.16 on 2022-12-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221209_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_title',
            field=models.CharField(choices=[('website design', 'website design'), ('database administrator', 'database administrator'), ('web research', 'web researcher'), ('web maintenance', 'web maintenance'), ('social media graphics', 'social media graphics'), ('logos and branding', 'logos and branding'), ('content expert', 'content expert')], max_length=30),
        ),
    ]
