# Generated by Django 3.2.16 on 2023-01-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_title',
            field=models.CharField(choices=[('web design', 'web design'), ('database administrator', 'database administrator'), ('web research', 'web researcher'), ('web maintenance', 'web maintenance'), ('social media graphics', 'social media graphics'), ('logos and branding', 'logos and branding'), ('content expert', 'content expert'), ('web hosting', 'web hosting'), ('web development', 'web development')], max_length=30),
        ),
    ]
