# Generated by Django 4.1.7 on 2023-06-09 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techorders", "0009_alter_comments_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 12, 32, 4, 954648)
            ),
        ),
    ]
